### Site metadata ###

title: Jekyll Blog Demo

# If you leave the description blank and publish to Github Pages, it will take your Git
# repo's description. At least the way the theme is setup.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: your-email@example.com
twitter_username: jekyllrb
github_username: jekyll

### Build settings ###

# Your website will be served on: {url}/{baseurl}
#     e.g. https://MichaelCurrin.github.com/jekyll-blog-demo
# So set this up using the next two parameters - url and baseurl.

# For URL, set base hostname AND protocol for your site, e.g. 'https://example.com'.
# And do not use a trailing forward slash.
#
# This value is ONLY applied for a prod build, that is:
#  - When deploying to Github Pages
#  - When wetting JEKYLL_ENV='production' as an environment variable locally
#    or on Netlify.
# It is recommended to set this at least for the canonical tag to be aware of the full domain,
# as that is recommended but not required for use by crawlers.
url: "https://michaelcurrin.github.io"

# If using Github Pages as a project site (USERNAME.github.io/my-project),
# this should be a forwardslash and the name of your repo - e.g. "/my-project"
# Your site will be served from this URL so all URLs on the page should relative to this too.
#
# If using a Github Pages as a user site (USERNAME.github.io/), or using Netlify, this can be empty.
baseurl: "/jekyll-blog-demo"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# This will use `/foo/` instead of `/foo.html` for paths.
permalink: pretty

# Include for processing

# Jekyll will not process paths starting an underscore or dot, except of course
# the underscore directories which it expects like _posts.
# You can force inclusions here. For example, if you don't want to keep your
# pages in the top-level directory.
# include:
#   - '_pages'

# Exclude from processing

# We want to only copy to the _site directory the files and directories which we want to be
# served publically.

# Jekyll will ignore files starting with a dot or underscore, but there are other files we
# want to ignore. So set these below in your `exclude `field. The Makefile line can be
# omitted if you do not have one. The slash is optional but helps indicate directories vs files.

exclude:
  - LICENSE
  - README.md
  - Makefile

  # In Jekyll 4, these are always excluded, so you never have to add them to your list.
  # But in Jekyll 3, these are needed:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
# For more precise control:
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Also add these if relevant for your project:
# - bin/
# - docs/
