### Site metadata ###

title: Jekyll Blog Demo
description: "Base for a static website blog - built with Jekyll and the default theme"

email:
twitter_username:
github_username: MichaelCurrin
rss: RSS

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/jekyll-blog-demo"

theme: minima

permalink: pretty

exclude:
  - docs/
  - LICENSE
  - Makefile
  - README.md
  - sample.png

  # In Jekyll 4, the ones below (and 'node_modules') will always get excluded, so you never have to add them to your list.
  # But in Jekyll 3, these are needed.
  - vendor/
  - Gemfile
  - Gemfile.lock
